import './globals.css';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import { NextBgStaticCss } from '@/../next-bg-image/src';

// eslint-disable-next-line
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: `Create Next App`,
  description: `Generated by create next app`,
};

export default function RootLayout({ children }: { children: React.ReactNode }): any {
  return (
    <html lang="en">
      <head>
        <NextBgStaticCss />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
